AllCops:
  TargetRubyVersion: 2.4.0
  Exclude:
    - "bin/**/*"
    - "config/initializers/*.rb"
    - "config/environments/*.rb"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "app/dashboards/*.rb"
    - "db/data/*.sql"
    - "z_ignore/**/*"
    - "node_modules/**/*"
    - "river/bin/**/*"
    - "river/config/initializers/*.rb"
    - "river/config/environments/*.rb"
    - "river/z_ignore/**/*"
    - "river/test/dummy/**/*"
    - "river/lib/river/**/*"

Style/Documentation:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "lib/tasks/**/*.rake"

Style/SymbolProc:
  Exclude:
    - "app/serializers/**/*.rb"

Style/StructInheritance:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
