AllCops:
  TargetRubyVersion: 2.4.0
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/*.rb'
    - 'config/environments/*.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'app/dashboards/*.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
