AllCops:
  TargetRubyVersion: 2.4.0
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/*.rb'
    - 'config/environments/*.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'app/dashboards/*.rb'
    - 'db/data/*.sql'
    - 'z_ignore/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/StructInheritance:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
