default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: caledna_development

test:
  <<: *default
  database: caledna_test

production:
  <<: *default
  database: caledna_production
  username: caledna
  url: <%= ENV['DATABASE_URL'] %>
